import React,{useState,useEffect}from'react';import{createRoot}from'react-dom/client';import{Heart,Gift,Calendar,Users,BarChart3,QrCode,Sparkles,Image,Play,Settings,LayoutDashboard,BookOpen,Mail,Lock,Music,Palette,Send}from'lucide-react';import QRCode from'qrcode';import'./style.css';
const A='/assets/';
const sample={bride:'Ada',groom:'Chinedu',event:'Wedding Surprise',date:'2026-09-20',story:'A cinematic journey through love, laughter, friendship and forever.',theme:'Luxury Rose Gold'};
function App(){const[page,setPage]=useState('home');return <><div className="ambient"></div><CursorFX/><nav><b className="brand"><Heart/> MomentCraft</b><div>{['home','builder','experience','guestbook','gifts','rsvp','dashboard','planner','admin','pricing'].map(p=><button onClick={()=>setPage(p)} className={page==p?'active':''}>{p}</button>)}</div></nav><main>{page==='home'&&<Home go={setPage}/>} {page==='builder'&&<Builder go={setPage}/>} {page==='experience'&&<Experience/>} {page==='guestbook'&&<Guestbook/>} {page==='gifts'&&<Gifts/>} {page==='rsvp'&&<RSVP/>} {page==='dashboard'&&<Dashboard/>} {page==='planner'&&<Planner/>} {page==='admin'&&<Admin/>} {page==='pricing'&&<Pricing/>}</main><footer>Frontend MVP only • No database yet • Payments, uploads and login are UI placeholders</footer></>}
function CursorFX(){useEffect(()=>{const move=e=>{let s=document.createElement('span');s.className='trail';s.style.left=e.clientX+'px';s.style.top=e.clientY+'px';document.body.appendChild(s);setTimeout(()=>s.remove(),700)};window.addEventListener('mousemove',move);return()=>window.removeEventListener('mousemove',move)},[]);return null}
function Home({go}){return <section className="hero"><div className="glass big"><p className="eyebrow">Emotion-as-a-Service MVP</p><h1>Create cinematic interactive experiences for weddings, birthdays, proposals and life events.</h1><p>Build premium memory journeys with games, reveals, countdowns, gifts, guestbook, RSVP, QR sharing and planner dashboards — all frontend-only for now.</p><div className="row"><button className="primary" onClick={()=>go('builder')}><Sparkles/>Create Experience</button><button onClick={()=>go('experience')}><Play/>View Guest Experience</button></div></div><div className="phone"><img src={A+'image1.png'}/><div className="phoneText">Someone has prepared something special just for you...</div></div></section>}
function Builder({go}){const steps=['Event Type','People','Media','Story','Questions','Theme','Preview','Publish'];return <section><h1>Experience Builder</h1><div className="grid">{steps.map((s,i)=><div className="card"><span className="num">{i+1}</span><h3>{s}</h3><p>{desc(s)}</p>{s==='Media'&&<p className="muted">Use assets: image1.png–image5.png, video1.mp4</p>}</div>)}</div><div className="glass"><h2>Publish Preview</h2><p>In MVP, publishing is simulated. In Version 1 this creates a unique URL, stores data in the database, and generates a QR code.</p><button className="primary" onClick={()=>go('experience')}>Preview Experience</button></div></section>}
function desc(s){return{EventType:'',People:'Add bride, groom, celebrant or recipient details.',Media:'Upload photos, videos, voice notes and music.',Story:'Enter the love story, memories and message tone.',Questions:'Build games, quizzes, memories and prompts.',Theme:'Pick luxury, floral, traditional, modern or cinematic.',Preview:'Test the exact guest experience before publishing.',Publish:'Generate link, QR code and share controls.'}[s.replace(' ','')]||'Choose the celebration category and template.'}
function Experience(){const[step,setStep]=useState(0);const[text,setText]=useState('');const[full,setFull]=useState(false);const slides=[['Welcome',`Someone has prepared something special for ${sample.bride}.`,A+'image1.png'],['Memory Unlock','Which one best describes your journey together?',A+'image2.png'],['Your Words','Type one thing you love most about this story.',A+'image3.png'],['Chapter Reveal',text?`You said: “${text}”. That is now part of this memory.`:'Every answer becomes part of the story.',A+'image4.png'],['Countdown','The final surprise is about to begin.',A+'image5.png'],['Final Video','Forever begins here.',A+'video1.mp4']];let s=slides[step];return <section className={full?'experience fullscreen':'experience'}><button className="mini" onClick={()=>setFull(!full)}>Fullscreen</button><Petals/><Particles/><div className="stage"><div className="media">{step===5?<video src={s[2]} controls autoPlay muted playsInline/>:<img src={s[2]}/>}</div><div className="overlay glass"><p className="eyebrow">{sample.event}</p><Type text={s[1]}/>{step===1&&<div className="choices">{['The beginning','The laughter','The growth','All of the above and more'].map(x=><button onClick={()=>setStep(2)}>{x}</button>)}</div>}{step===2&&<><input placeholder="Type your answer here..." value={text} onChange={e=>setText(e.target.value)}/><button className="primary" onClick={()=>setStep(3)}>Enter</button></>}{![1,2].includes(step)&&step<5&&<button className="primary" onClick={()=>setStep(step+1)}>{step===4?'Start Final Reveal':'Continue'}</button>}{step===5&&<button onClick={()=>setStep(0)}>Replay</button>}</div></div></section>}
function Type({text}){const[out,setOut]=useState('');useEffect(()=>{setOut('');let i=0,t=setInterval(()=>{setOut(text.slice(0,++i));if(i>=text.length)clearInterval(t)},25);return()=>clearInterval(t)},[text]);return <h1>{out}</h1>}
function Petals(){return <>{Array.from({length:18}).map((_,i)=><i className="petal" style={{left:i*6+'%',animationDelay:i*.5+'s'}}/> )}</>}
function Particles(){return <>{Array.from({length:35}).map((_,i)=><i className="particle" style={{left:Math.random()*100+'%',top:Math.random()*100+'%',animationDelay:i*.2+'s'}}/> )}</>}
function Guestbook(){return <section><h1>Digital Guestbook</h1><div className="grid"><div className="glass"><input placeholder="Your name"/><textarea placeholder="Leave a wish, prayer or memory..."/><button><Send/>Submit Demo</button></div>{['Wishing you joy forever.','This love is beautiful.','May this home be blessed.'].map(m=><div className="card"><h3>Guest Message</h3><p>{m}</p></div>)}</div></section>}
function Gifts(){return <section><h1>Gift Centre</h1><div className="grid">{['Send Cash Gift','Buy Flowers','Sponsor Honeymoon','Buy Dinner Voucher','Group Gift','Escrow Surprise'].map(x=><div className="card"><Gift/><h3>{x}</h3><p>UI only in MVP. Paystack/Opay/Moniepoint integration comes in Version 1.</p><button>Demo Button</button></div>)}</div></section>}
function RSVP(){return <section><h1>RSVP & Invitation</h1><div className="glass"><input placeholder="Guest name"/><select><option>Attending</option><option>Not attending</option><option>Maybe</option></select><input placeholder="Number of guests"/><button>Submit RSVP Demo</button></div><QR/></section>}
function QR(){const[url,setUrl]=useState('');useEffect(()=>{QRCode.toDataURL(location.href).then(setUrl)},[]);return <div className="card"><QrCode/><h3>QR Code</h3>{url&&<img className="qr" src={url}/>}<p>Scan to open this MVP.</p></div>}
function Dashboard(){return <Portal title="Customer Dashboard" items={['My Experiences','Create New','Drafts','Published','Media Library','Analytics Placeholder','Payments Placeholder','Settings']}/>}function Planner(){return <Portal title="Planner Dashboard" items={['Clients','Experiences','White Label Settings','Templates','Team','Reports','Subscriptions','Support']}/>}function Admin(){return <Portal title="Admin Dashboard" items={['Users','Experiences','Themes','Templates','Payments','Reviews','Analytics','System Settings']}/>}function Portal({title,items}){return <section><h1>{title}</h1><div className="grid">{items.map((x,i)=><div className="card"><LayoutDashboard/><h3>{x}</h3><p>{i%2?'Version 1 will connect this to database and APIs.':'MVP interface placeholder for product demonstration.'}</p></div>)}</div></section>}
function Pricing(){return <section><h1>Pricing</h1><div className="grid"><Price name="Basic" price="₦10k"/><Price name="Premium" price="₦30k"/><Price name="Luxury" price="₦75k+"/><Price name="Planner SaaS" price="₦50k/mo"/></div></section>}function Price(p){return <div className="card price"><h2>{p.name}</h2><h1>{p.price}</h1><p>Demo pricing for market validation.</p><button>Choose</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
